# Generated by Django 3.1.3 on 2020-11-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_paciente_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caso',
            old_name='paciente',
            new_name='pacientes',
        ),
    ]
